### ISSUE TITLE
做github登陆 出现set_cookie() got an unexpected keyword argument 'samesite'

### ISSUE THREAD

**Issue by wolflikai** [greyli/catchat#7]
经过debug 发现
`providers[provider_name].authorize(callback=callback_url)`
得到的url是可以到认证页面 但视图函数返回报如图错误

**Comment by greyli** [comment]
Werkzeug 版本是否小于 0.14？如果是的话，更新后再试试。

**Comment by wolflikai** [comment]
Werkzeug 0.14.1 flask1.0.2 不知道是不是flask-Oauthlib 版本问题

**Comment by wolflikai** [comment]
![image](https://user-images.githubusercontent.com/24989507/52051664-2e5e6500-258f-11e9-824a-419dcb415351.png)
![image](https://user-images.githubusercontent.com/24989507/52051674-33bbaf80-258f-11e9-9687-45049a356c95.png)
![image](https://user-images.githubusercontent.com/24989507/52051681-36b6a000-258f-11e9-8bc6-5548cdcdd4e2.png)

以上为debug图片 找不到原因很苦恼:(

**Comment by greyli** [comment]
请发一下完整的错误输出，粘贴为文字。

**Comment by wolflikai** [comment]
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\app.py", line 2114, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\flask\sessions.py", line 384, in save_session
    samesite=samesite
TypeError: set_cookie() got an unexpected keyword argument 'samesite'
```
奇怪的是 在mac下是没有报错的:(

**Comment by greyli** [comment]
从报错看猜测还是 Werkzeug 版本问题。可以试着创建一个虚拟环境，重装依赖试下。

**Comment by wolflikai** [comment]
问题解决了 是依赖问题  谢谢李辉大大:)
